# Generated by Django 4.1 on 2022-09-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='Email',
            new_name='email',
        ),
    ]
