# Generated by Django 4.1.1 on 2022-09-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feature')),
                ('icon', models.FileField(max_length=255, upload_to='feature')),
                ('icon_background', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('testimonial_description', models.TextField()),
                ('testimonial_author', models.CharField(max_length=255)),
                ('author_designation', models.CharField(max_length=255)),
                ('testimonial_logo', models.FileField(max_length=255, upload_to='feature')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.FileField(max_length=255, upload_to='cusomer'),
        ),
    ]
